"""1256 三大模块正式数据收敛治理契约。"""

from .contracts import (
    ALLOWED_TRANSITIONS,
    AssetRecord,
    AssetRegistry,
    CaptionRecord,
    DirectorGroup,
    DirectorLockedManifest,
    DirectorShot,
    EditBinding,
    EditManifest,
    GovernanceContractError,
    MaterialRequirement,
    ProjectManifest,
    TimeWindow,
    assert_transition,
)
from .invalidation import invalidation_scope
from .director_convergence import (
    DirectorConvergenceError,
    DirectorConvergenceInput,
    DirectorConvergenceReport,
    DirectorRouteSpec,
    DirectorSubplanReceipt,
    DirectorVisualSpec,
    lock_director_manifest,
    validate_director_convergence,
)
from .director_submodule_closure import (
    DIRECTOR_SUBMODULE_NODE_IDS,
    DirectorNodeClosure,
    DirectorSubmoduleClosure,
    DirectorSubmoduleClosureError,
    DirectorSubmoduleClosureReport,
    build_director_submodule_closure,
)
from .director_context import (
    DirectorContext,
    NarrativeLedger,
    ShotLedger,
    TimingLedger,
    VisualRouteLedger,
)
from .director_runtime_lock import DirectorRuntimeLockError, build_director_locked_manifest
from .digital_human_governance import (
    DEFAULT_MAX_DIGITAL_HUMAN_SHOT_RATIO,
    DigitalHumanGovernanceError,
    normalize_digital_human_policy,
    validate_digital_human_slots,
)
from .node_registry import (
    MODULES,
    MODULE_GATES,
    NODE_CONTRACTS,
    NodeContract,
    build_module_governance_snapshot,
    get_module_nodes,
    validate_node_registry,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AssetRecord",
    "AssetRegistry",
    "CaptionRecord",
    "DirectorGroup",
    "DirectorLockedManifest",
    "DirectorShot",
    "EditBinding",
    "EditManifest",
    "GovernanceContractError",
    "MaterialRequirement",
    "ProjectManifest",
    "TimeWindow",
    "assert_transition",
    "DirectorConvergenceError",
    "DirectorConvergenceInput",
    "DirectorConvergenceReport",
    "DirectorRouteSpec",
    "DirectorSubplanReceipt",
    "DirectorVisualSpec",
    "lock_director_manifest",
    "validate_director_convergence",
    "DIRECTOR_SUBMODULE_NODE_IDS",
    "DirectorNodeClosure",
    "DirectorSubmoduleClosure",
    "DirectorSubmoduleClosureError",
    "DirectorSubmoduleClosureReport",
    "build_director_submodule_closure",
    "DirectorContext",
    "NarrativeLedger",
    "ShotLedger",
    "TimingLedger",
    "VisualRouteLedger",
    "invalidation_scope",
    "MODULES",
    "MODULE_GATES",
    "NODE_CONTRACTS",
    "NodeContract",
    "build_module_governance_snapshot",
    "get_module_nodes",
    "validate_node_registry",
    "DirectorRuntimeLockError",
    "build_director_locked_manifest",
    "DEFAULT_MAX_DIGITAL_HUMAN_SHOT_RATIO",
    "DigitalHumanGovernanceError",
    "normalize_digital_human_policy",
    "validate_digital_human_slots",
]
