"""账号认知知识库的本地契约与 Obsidian 存储层。

该包只负责可追溯知识资产的建模、校验和本地 Markdown 读写；
不会自动调用模型，也不会修改现有选题、文案或导演生产状态。
"""

from .contracts import (
    ALLOWED_CONTENT_GRADES,
    ALLOWED_KNOWLEDGE_STATUSES,
    ALLOWED_PERFORMANCE_GRADES,
    CognitionCard,
    GradeCard,
    KnowledgeContractError,
    WorkCard,
    build_work_id,
    utc_now,
)
from .obsidian_repository import (
    KnowledgeConflictError,
    ObsidianRepository,
    ObsidianRepositoryError,
    VaultConfigError,
)
from .distillation import (
    AccountDistillationProvider,
    DistillationProvider,
    DistillationProviderRequired,
    build_account_distillation,
    build_cognition_card_from_distillation,
    build_work_card_from_distillation,
    distill_account_with_provider,
    distill_with_provider,
    write_account_distillation,
)
from .grading import GRADE_WEIGHTS, apply_manual_grade, is_normal_retrieval_eligible
from .orchestrator import (
    CopywritingProvider,
    CopywritingProviderRequired,
    build_topic_plan_from_index,
    run_copywriting_provider,
)
from .lab_store import LabArtifactStore, LabArtifactStoreError
from .corpus_import import CorpusImportItem, CorpusImportReport, discover_corpus_files, import_corpus
from .surface_analysis import analyze_corpus, analyze_texts
from .offline_candidates import (
    OFFLINE_CANDIDATE_METHOD,
    OFFLINE_CANDIDATE_STATUS,
    build_offline_candidate_bundle,
    write_offline_candidate_notes,
)
from .style_package_upgrade import (
    DERIVED_EVIDENCE_QUALITY,
    DERIVED_SOURCE_KIND,
    StylePackageImportItem,
    StylePackageImportReport,
    UPGRADE_SCHEMA_VERSION,
    build_profile_upgrade_candidate,
    import_style_package_rewrites,
    load_style_package_rewrites,
    run_style_package_upgrade,
    write_profile_upgrade_candidate,
)
from .model_providers import (
    AccountKnowledgeModelError,
    AccountKnowledgeModelProvider,
    apply_api_management_runtime,
    apply_api_management_model_runtime,
    build_account_distillation_prompts,
    build_topic_synthesis_prompts,
    build_work_distillation_prompts,
    merge_topic_synthesis,
)
from .production_bridge import (
    MIN_PRODUCTION_TRANSCRIPT_CHARS,
    PRODUCTION_PROMPT_VERSION,
    ProductionBridgeError,
    resolve_account_id,
    sync_collection_to_obsidian,
)
from .evidence import (
    DISTILLATION_JOB_SCHEMA_VERSION,
    EVIDENCE_SCHEMA_VERSION,
    EVIDENCE_STATUSES,
    JOB_STATUSES,
    DistillationJob,
    EvidenceSet,
    RawSource,
    build_evidence_set_id,
)
from ..knowledge_source_registry import (
    KnowledgeSourceError,
    KnowledgeSourceRegistry,
    SOURCE_KINDS,
    SOURCE_STATUSES,
    SOURCE_STATUS_LABELS,
    detect_source,
)

__all__ = [
    "ALLOWED_CONTENT_GRADES",
    "ALLOWED_KNOWLEDGE_STATUSES",
    "ALLOWED_PERFORMANCE_GRADES",
    "CognitionCard",
    "AccountDistillationProvider",
    "CorpusImportItem",
    "CorpusImportReport",
    "CopywritingProvider",
    "CopywritingProviderRequired",
    "DistillationProvider",
    "DistillationProviderRequired",
    "GradeCard",
    "GRADE_WEIGHTS",
    "LabArtifactStore",
    "LabArtifactStoreError",
    "KnowledgeContractError",
    "KnowledgeConflictError",
    "ObsidianRepository",
    "ObsidianRepositoryError",
    "VaultConfigError",
    "WorkCard",
    "apply_manual_grade",
    "build_cognition_card_from_distillation",
    "build_account_distillation",
    "build_work_card_from_distillation",
    "build_topic_plan_from_index",
    "build_work_id",
    "analyze_corpus",
    "analyze_texts",
    "OFFLINE_CANDIDATE_METHOD",
    "OFFLINE_CANDIDATE_STATUS",
    "build_offline_candidate_bundle",
    "write_offline_candidate_notes",
    "DERIVED_EVIDENCE_QUALITY",
    "DERIVED_SOURCE_KIND",
    "StylePackageImportItem",
    "StylePackageImportReport",
    "UPGRADE_SCHEMA_VERSION",
    "build_profile_upgrade_candidate",
    "import_style_package_rewrites",
    "load_style_package_rewrites",
    "run_style_package_upgrade",
    "write_profile_upgrade_candidate",
    "AccountKnowledgeModelError",
    "AccountKnowledgeModelProvider",
    "apply_api_management_runtime",
    "apply_api_management_model_runtime",
    "build_account_distillation_prompts",
    "build_topic_synthesis_prompts",
    "build_work_distillation_prompts",
    "merge_topic_synthesis",
    "MIN_PRODUCTION_TRANSCRIPT_CHARS",
    "PRODUCTION_PROMPT_VERSION",
    "ProductionBridgeError",
    "resolve_account_id",
    "sync_collection_to_obsidian",
    "DISTILLATION_JOB_SCHEMA_VERSION",
    "EVIDENCE_SCHEMA_VERSION",
    "EVIDENCE_STATUSES",
    "JOB_STATUSES",
    "DistillationJob",
    "EvidenceSet",
    "RawSource",
    "build_evidence_set_id",
    "distill_with_provider",
    "distill_account_with_provider",
    "discover_corpus_files",
    "import_corpus",
    "is_normal_retrieval_eligible",
    "write_account_distillation",
    "run_copywriting_provider",
    "utc_now",
    "KnowledgeSourceError",
    "KnowledgeSourceRegistry",
    "SOURCE_KINDS",
    "SOURCE_STATUSES",
    "SOURCE_STATUS_LABELS",
    "detect_source",
]
